### ISSUE TITLE
`inxflg` defined in isac.py function but not when called in main.py | PR # 72

### ISSUE THREAD

**Issue by MuhammadHammad001** [riscv-software-src/riscv-isac#83]
@anuani21

This issue is related to the [PR #72](https://github.com/riscv-software-src/riscv-isac/pull/72)

While running the coverage using the `risc-v isac` command, I get the following error:
```objective-c
Traceback (most recent call last):
  File "/usr/local/bin/riscv_isac", line 33, in <module>
    sys.exit(load_entry_point('riscv-isac', 'console_scripts', 'riscv_isac')())
  File "/home/hammad/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/hammad/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/hammad/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hammad/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hammad/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/hammad/mcause_check/new/virtual_memory_implementation/riscv-isac/riscv_isac/main.py", line 149, in coverage
    isac(output_file,elf,trace_file, window_size, preprocessing(expand_cgf(cgf_file,int(xlen),int(flen),log_redundant), header_file, cgf_macro), parser_name, decoder_name, parser_path, decoder_path, detailed, test_label,
TypeError: isac() missing 1 required positional argument: 'procs'
```

The issue I saw is that you have used the `inxFlg` in the **isac.py**:
https://github.com/riscv-software-src/riscv-isac/blob/65a22dffda0fe2aa712e8437421ed3714c863a4e/riscv_isac/isac.py#L8-L9

But, it is not used in the **main.py**:
https://github.com/riscv-software-src/riscv-isac/blob/65a22dffda0fe2aa712e8437421ed3714c863a4e/riscv_isac/main.py#L134-L138

I am unable to understand whether the issue is on my end or in the merged PR. Please correct me if I am misunderstanding this.

**Comment by anuani21** [comment]
Yes we need to define inxFlg flag in main.py.  In previous PR it is missed
it seems.I had updated main.py and raised a new PR.(#84)
